package com.wgc.cmwgc.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wgc.cmwgc.db.DeviceDataEntity;

import com.wgc.cmwgc.db.DeviceDataEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig deviceDataEntityDaoConfig;

    private final DeviceDataEntityDao deviceDataEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        deviceDataEntityDaoConfig = daoConfigMap.get(DeviceDataEntityDao.class).clone();
        deviceDataEntityDaoConfig.initIdentityScope(type);

        deviceDataEntityDao = new DeviceDataEntityDao(deviceDataEntityDaoConfig, this);

        registerDao(DeviceDataEntity.class, deviceDataEntityDao);
    }
    
    public void clear() {
        deviceDataEntityDaoConfig.clearIdentityScope();
    }

    public DeviceDataEntityDao getDeviceDataEntityDao() {
        return deviceDataEntityDao;
    }

}
